server:
  port: 8080

#  url的前缀
  servlet:
    context-path: /wenda
#
mybatis:
  config-location: classpath:mybatis-config.xml

#
# mysql
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wenda?characterEncoding=utf-8&useSSL=false
    password: 123456
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource





#  freemarker config
  freemarker:
    cache: false
    check-template-location: true
    content-type: text/html
    charset: UTF-8
    template-loader-path: classpath:/templates/
    suffix: .html
#
## redis
#redis:
#host: 47.106.215.221
#port: 6379
#timeout: 10000
#password: 123456
#jedis:
#pool:
#min-idle: 0
#max-idle: 8
#max-active: 100
#max-wait: 10000
